/*
 * error_codes.h
 *
 *  Created on: Dec 17, 2024
 *      Author: Barabash
 */

#ifndef INC_ERROR_CODES_H_
#define INC_ERROR_CODES_H_


typedef enum ReturnCode{
	G_ERROR = 0x00,
	G_SUCCESS = 0x01,
	C_MOUNT_ERROR = 0x02,
	G_FILE_WRITE = 0x03,
	G_FILE_READ = 0x04,
	G_COM_OVERFLOW = 0x05,
	G_COM_TRANSMIT = 0x06,
	G_COM_RECEIVE = 0x07,
	C_RTC_ERROR = 0x08,
	C_UART_TRANSMIT = 0x09,
	C_UART_RECEIVE = 0x0A,
	C_UART_HANDLE = 0x0B,
	G_SERVO_WRTIE = 0x0C,
	G_SERVO_READ = 0x0D,
	C_ACC_HANDLE = 0x0E,
	C_I2C_TRANSMIT = 0x0F,
	C_I2C_RECEIVE = 0x10,
	G_ACC_READ = 0x11,
	C_CAN_TXADD = 0x12,
	C_CAN_OVERFLOW = 0x13,
	C_CAN_CONFIG = 0x14,
	C_CAN_READ = 0x15,
	C_COM_DECODE = 0x16,
	G_SD_INITIALIZED = 0x17,
	G_SD_NOT_INITIALIZED = 0x18
}ReturnCode;


#endif /* INC_ERROR_CODES_H_ */
